# Site
title: Mr.可豆
description: 可豆先生的生活，技术和学习
show_downloads: false
welcome_message: Quality-focused Systems Engineer, support in different OS based system and Virtualization.
permalink: /:year/:month/:title/
## https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

social:
  linkedin: https://www.linkedin.com/in/nick-su-217027ab/
  mail: nicksu383@gmail.com

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

