# Site
title: Mr.可豆
subtitle: 可豆先生的生活，技术和学习
welcome_message: Quality-focused Systems Engineer, support in different OS based system and Virtualization.
permalink: /:year/:month/:title/
theme: jekyll-theme-hacker

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

